package tex

// LatexMathReplacements maps Unicode characters to their LaTeX equivalents
// TODO: clean up
var LatexMathReplacements = map[rune]string{
	'→': "\\to",
	'⟶': "\\goesto",
	'↦': "\\mapsto",
	'≠': "\\neq",
	'∈': "\\in",
	'∉': "\\not\\in",
	'⊃': "\\supset",
	'⊇': "\\supseteq",
	'⊂': "\\subset",
	'⊆': "\\subseteq",
	'⊊': "\\subsetneq",
	'⊄': "\\not\\subset",
	'∅': "\\varnothing",
	'∪': "\\cup",
	'⋃': "\\bigcup",
	'∩': "\\cap ",
	'⋂': "\\bigcap",
	'×': "\\times ",
	'★': "\\star",
	'𝓜': "\\mathcal{A}",
	'ℬ': "\\mathcal{B}",
	'𝓞': "\\mathcal{C}",
	'𝓟': "\\mathcal{D}",
	'ℰ': "\\mathcal{E}",
	'ℱ': "\\mathcal{F}",
	'𝓢': "\\mathcal{G}",
	'ℋ': "\\mathcal{H}",
	'ℐ': "\\mathcal{I}",
	'𝓥': "\\mathcal{J}",
	'𝓦': "\\mathcal{K}",
	'ℒ': "\\mathcal{L}",
	'ℳ': "\\mathcal{M}",
	'𝓩': "\\mathcal{N}",
	'𝓪': "\\mathcal{O}",
	'𝓫': "\\mathcal{P}",
	'𝓬': "\\mathcal{Q}",
	'ℛ': "\\mathcal{R}",
	'𝓮': "\\mathcal{S}",
	'𝓯': "\\mathcal{T}",
	'𝓰': "\\mathcal{U}",
	'𝓱': "\\mathcal{V}",
	'𝓲': "\\mathcal{W}",
	'𝓳': "\\mathcal{X}",
	'𝓴': "\\mathcal{Y}",
	'𝓵': "\\mathcal{Z}",
	'ℓ': "\\ell",
	//	'∕': "/", causes confusion with </div>
	'∏': "\\prod",
	'∑': "\\sum",
	'≈': "\\approx",
	'≡': "\\equiv",
	'≪': "\\ll",
	'≫': "\\gg",
	'≦': "\\leqq",
	'≧': "\\geqq",
	'≥': "\\geq",
	'≤': "\\leq",
	'≺': "\\prec",
	'≻': "\\succ",
	'≼': "\\preceq",
	'≽': "\\succeq",
	'∫': "\\int ",
	'∀': "\\forall",
	'∃': "\\exists ",
	'∄': "\\not\\exists",
	'∞': "\\infty",
	'∝': "\\propto",
	'∘': "\\circ",
	'⋮': "\\vdots",
	'⋯': "\\cdots",
	'⋱': "\\ddots",
	'·': "\\cdot",
	'∼': "\\sim",
	'√': "\\sqrt",
	'±': "\\pm",
	'∓': "\\mp",
	'𝗽': "\\R",
	'𝗼': "\\Q",
	'𝗿': "\\N ",
	'𝗥': "\\Z",
	'𝗢': "\\C",
	'𝗣': "\\mathbfsf{D}",
	'𝗩': "\\F",
	'𝗤': "\\E",
	'𝗷': "\\mathbfsf{P}",
	'𝗺': "\\mathbfsf{S}",
	'𝗻': "\\mathbfsf{T}",
	'𝔑': "\\mathbf{R}",
	'𝔒': "\\mathbf{S}",
	'𝔈': "\\mathbf{E}",
	'𝔢': "\\mathbf{e}",
	'𝔏': "\\mathbf{P}",
	'𝟑': "\\mathbf{1}",
	'𝟐': "\\mathbf{0}",
	'𝔊': "\\mathbf{K}",
	'𝔔': "\\mathbf{U}",
	'𝔖': "\\mathbf{W}",
	'𝔗': "\\mathbf{X}",
	'𝔘': "\\mathbf{Y}",
	'𝔙': "\\mathbf{Z}",
	'𝔰': "\\mathbf{w}",
	'𝔱': "\\mathbf{x}",
	'𝔲': "\\mathbf{y}",
	'𝔳': "\\mathbf{z}",
	'∇': "\\nabla ",
	'∂': "\\partial ",
	'α': "\\alpha",
	'β': "\\beta",
	'ψ': "\\psi",
	'δ': "\\delta",
	'ε': "\\varepsilon",
	'ϵ': "\\epsilon",
	'φ': "\\phi",
	'Φ': "\\Phi",
	'γ': "\\gamma",
	'η': "\\eta",
	'ι': "\\iota",
	'ξ': "\\xi",
	'κ': "\\kappa",
	'λ': "\\lambda",
	'Λ': "\\Lambda ",
	'μ': "\\mu",
	'ν': "\\nu",
	'ο': "\\omicron",
	'π': "\\pi",
	'ρ': "\\rho",
	'σ': "\\sigma",
	'Σ': "\\Sigma",
	'⇒': "\\Rightarrow",
	'⇐': "\\Leftarrow",
	'←': "\\leftarrow",
	'⇌': "\\rightleftharpoons",
	'τ': "\\tau",
	'θ': "\\theta",
	'Θ': "\\Theta",
	'ω': "\\omega",
	'Ω': "\\Omega",
	//	'ς':
	'χ': "\\chi",
	'υ': "\\upsilon",
	'ζ': "\\zeta",
	'⟹': "\\implies",
	'Ξ': "\\Xi",
	//	'½': "\\nicefrac{1}{2}", // does not work?
	'½': "1/2",
	'¼': "1/4",
	'⅙': "1/6",
	'⅓': "1/3",
	'⅛': "1/8",
	'¾': "3/4",
	'∖': "\\setminus", // does not work?
	'…': "\\dots",
	'∔': "\\dotplus",
	'|': "\\mid ",
	'⟂': "\\perp ",
	'Π': "\\Pi",
	'¬': "\\neg",
	'∨': "\\lor",
	'∧': "\\land",
	'Ψ': "\\Psi",
	'Γ': "\\Gamma",
	'Δ': "\\Delta",
	'∆': "\\symdiff",
	'⊔': "\\sqcup",
	'ℑ': "\\Im",
	'ℜ': "\\Re",
	'∠': "\\angle",
	'⊤': "\\top ",
	'⊥': "\\perp ",
	'⟨': "\\langle ",
	'⟩': "\\rangle ",
	'｛': "\\{",
	'｝': "\\}",
	'≔': "\\coloneqq",
	'⊨': "\\models",
	'⊕': "\\oplus",
	'°': "^{\\circ}", // TODO: is this what we want?
}
